name: Build and deploy slatebox-prod-collab to hetzner k3
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.HETZNER_KUBE_CONFIG_PROD }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          export RELEASE=$(awk -F'[*…]' '/###*/{print $(NF-1)}' CHANGELOG.md | xargs | awk '{split($0, array, /##/); print array[3]}' | xargs | awk '{split($0, a, /-/); print a[1]}' | xargs | awk '{sub(/\[/,"")sub(/\]/,"")}1' $1)

          docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }}:$RELEASE .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }}:$RELEASE
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }}:$RELEASE ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }}:latest

          # set up collab secrets
          sed -i'' -e "s/MONGO_URL_SECRET/${{ secrets.PROD_MONGO_URL }}/g" -e "s/API_GEN_KEY_SECRET/${{ secrets.API_GEN_KEY }}/g" -e "s/API_KEYS_SECRET/${{ secrets.API_KEYS }}/g" ./k3/prod.yml

          # set up docker creds
          # echo 'SECOND sed $RELEASE DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} DOCKER_HUB_PROD_COLLAB_REPOSITORY: ${{ secrets.DOCKER_HUB_PROD_COLLAB_REPOSITORY }} DOCKER_CONFIG: ${{ secrets.DOCKER_CONFIG }}'
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e 's/DOCKER_HUB_USERNAME/${{ secrets.DOCKER_HUB_USERNAME }}/g' -e 's/DOCKER_HUB_PROD_REPOSITORY/${{ secrets.DOCKER_HUB_PROD_REPOSITORY }}/g' -e "s/IMAGE_LABEL/$RELEASE/g" -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" ./k3/prod.yml

          # apply both
          echo 'docker config is: ${{ DOCKER_CONFIG }}'

          kubectl apply -f ./k3/prod.yml
